// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWQIOQc0vxHgVjtCpFyt6V4d0hmrCsUEM',
    appId: '1:699948710293:web:3205db51fd92af667e1e9c',
    messagingSenderId: '699948710293',
    projectId: 'gamblers-gaming-test',
    authDomain: 'gamblers-gaming-test.firebaseapp.com',
    storageBucket: 'gamblers-gaming-test.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaowo7vzFEcIxKJyJI9ThDZur8WNKgcz0',
    appId: '1:699948710293:android:cc62b92f28e627de7e1e9c',
    messagingSenderId: '699948710293',
    projectId: 'gamblers-gaming-test',
    storageBucket: 'gamblers-gaming-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6hl761kFVyepJeBV6TF9Y8pMXV-rv6xg',
    appId: '1:699948710293:ios:0bbc8bef5caaef647e1e9c',
    messagingSenderId: '699948710293',
    projectId: 'gamblers-gaming-test',
    storageBucket: 'gamblers-gaming-test.appspot.com',
    iosClientId: '699948710293-un06q389g1q4tke7asd3qmu991qpo7cs.apps.googleusercontent.com',
    iosBundleId: 'com.example.gamblersgaming',
  );
}
